
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
        - name: flaskapp
          image: <account-id>.dkr.ecr.us-east-1.amazonaws.com/flaskapp:latest
          ports:
            - containerPort: 5000
