global:
  scrape_interval: 15s  # Collect metrics every 15 seconds

scrape_configs:
  - job_name: 'application'
    static_configs:
      - targets: ['localhost:9090']  # Replace with your app's metrics endpoint
