apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: bW9uZ291c2Vy  # Base64 encoded 'mongouser'
  MONGO_INITDB_ROOT_PASSWORD: c2VjcmV0cGFzcw==  # Base64 encoded 'secretpass'
